kind: GitRepo
apiVersion: fleet.cattle.io/v1alpha1
metadata:
  name: stable-diffusion
  namespace: fleet-default
spec:
  repo: https://github.com/atoy3731/stable-diffusion-webui-kubernetes.git
  branch: master
  targets:
  - name: main
    clusterSelector:
      matchLabels:
        stable-diffusion: enabled
  paths:
  - ./kubernetes