---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.models.pvcName }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.models.capacity }}